### ISSUE TITLE
AzureDoom- Doom Mod causes crashing with other mods

### ISSUE THREAD

**Issue by BedrockLegends** [AzureDoom/AzureDoom-Doom-Mod#10]
[crash-2020-10-02_17.24.43-client.txt](https://github.com/AzureDoom/AzureDoom-Doom-Mod/files/5320583/crash-2020-10-02_17.24.43-client.txt)
[crash-2020-10-02_17.05.31-fml.txt](https://github.com/AzureDoom/AzureDoom-Doom-Mod/files/5320585/crash-2020-10-02_17.05.31-fml.txt)
[debug.log](https://github.com/AzureDoom/AzureDoom-Doom-Mod/files/5320586/debug.log)

**Comment by AzureDoom** [comment]
You fixed it?

**Comment by AzureDoom** [comment]
Guessing yes as none of those logs are my mod.
