### ISSUE TITLE
1.16.3 Fabric - Mod causes CTD on startup.

### ISSUE THREAD

**Issue by matty45** [AzureDoom/AzureDoom-Doom-Mod#12]
Here is the log: https://paste.ee/p/ApBGQ

Here is another log with curios api added: https://paste.ee/p/QjOwp

Are there any dependencies that you forgot to mention somewhere? I cannot find them on the main download page.

**Comment by AzureDoom** [comment]
Right on the download page of the file 
![image](https://user-images.githubusercontent.com/7415711/96199795-51c57100-0f26-11eb-8e91-29053bc74192.png)
