### ISSUE TITLE
Client CTD going into nether 1.16.4 GeoModelException

### ISSUE THREAD

**Issue by IchigoGames** [AzureDoom/AzureDoom-Doom-Mod#18]
Minecraft 1.16.4
Forge 35.1.0
Mod version MCDoom-Mod-1.16.4-3.4.7
desc all i did was update the mod load in and go to nether as soon as i got there and turned to look at some doom mobs i crashed
crash https://pastebin.com/0BLXNL89

**Comment by AzureDoom** [comment]
Looks like your jar is broken? It's for sure in the jar I uploaded as I just doubled checked and I created a fresh pack in GD and downloaded everything fresh.
![2020-11-22_00 52 22](https://user-images.githubusercontent.com/7415711/99896277-07d65600-2c5d-11eb-9e62-1c80554f75cb.png)

**Comment by IchigoGames** [comment]
you where right
