### ISSUE TITLE
Suggestions More config options 1.16.4

### ISSUE THREAD

**Issue by IchigoGames** [AzureDoom/AzureDoom-Doom-Mod#19]
atm on my modpack -server we have so meany doom mobs spawning that normal mobs like ghasts dont have a chance to spawn can you add a config that lets you lower the mob spawn rate or a limit you can set to how meany can sapwn in nether. let me know if i missed something in options

**Comment by IchigoGames** [comment]
still waiting on this mobs spawn to much need config to lower spawn rates

**Comment by AzureDoom** [comment]
It's in the next update, I'm currently waiting on the final model I need for the next update.

**Comment by SheerAwesomeness** [comment]
> It's in the next update, I'm currently waiting on the final model I need for the next update.

Has this been developed already? I may look into creating a PR for configurable biome dictionary, spawn weights, attack dmg, hp & speed, Y levels etc. for each entity.
