### ISSUE TITLE
Bug: Autolock activates when you swap in and out of minecraft

### ISSUE THREAD

**Issue by mactso** [AzureDoom/AzureDoom-Doom-Mod#20]
Version 1.16.3,1.16.4 forge 34.1.42 and latest 35.

When first entering the game, autolock locks onto the nearest creature without any message or indicator if there is a creature within range.

Once playing, if you swap in and out of minecraft to another application, autolock turns on when you swap back to Minecraft if there is a creature within range.

Please consider adding a way to disable autolock as a short term measure until the bug is fixed- I'm guess it's needed to fight some of the doom mobs.

Please considering adding a message or indicator when the player presses the autolock key along the lines of "You have activated autolock with the "p" key.  Press again to deactivate." or an autolock icon (but that's screengui so it's going to be harder tho slicker- a message is an easier quick and dirty solution).

Really excited about the mod.  Hope this gets fixed soon.   Some folks getting irritated about it so it has a high negative impact on play experience.

**Comment by AzureDoom** [comment]
It's because its configured to the Tab key. You can reconfigure it in the controls menu.

**Comment by mactso** [comment]
Odd.  I thought I had it configured to the "p" key when this was happening but I will confirm.  Everyone else was using default settings.  Good catch!
