### ISSUE TITLE
Just a personal issue on server

### ISSUE THREAD

**Issue by BreazyLantern** [AzureDoom/AzureDoom-Doom-Mod#25]
It seems the mod was pretty big that the private server I this mod on with my friend will make it so that it gives out the poorly compressed packet limit error. This is just a personal issue otherwise and just means that I have to many mods to actually make this viable to play with considering that the bigger packets mod is not available for 1.16.4. You can close this issue right away if you'd like. Just like to say this is an amazing mod, thank you for your wonderful mods.

**Comment by AzureDoom** [comment]
I don't understand the issue here?
