### ISSUE TITLE
Crash With Shatter Mod

### ISSUE THREAD

**Issue by IRonicBruh** [AzureDoom/AzureDoom-Doom-Mod#26]
After killing any Doom enemies the game will crash.
Crash Report: https://gist.github.com/IRonicBruh/3c3d930351b982906222139793cd8d13

**Comment by AzureDoom** [comment]
This would need fixed on Shatters side not mine

**Comment by IRonicBruh** [comment]
copy, and damn your fast.

**Comment by AzureDoom** [comment]
I have this github linked to my discord and currently coding haha
