### ISSUE TITLE
Armours Missing Texture

### ISSUE THREAD

**Issue by TheRealFroggo** [AzureDoom/AzureDoom-Doom-Mod#28]
![image](https://user-images.githubusercontent.com/50634225/107853450-2c694680-6de4-11eb-9aec-5b51925ad29f.png)
Three different armours, all missing textures, both on armour stands, and on players.

**Comment by AzureDoom** [comment]
What verison and using optifine?

**Comment by TheRealFroggo** [comment]
Most Recent, and Yes, I am

**Comment by AzureDoom** [comment]
Test without Optifine please

**Comment by TheRealFroggo** [comment]
Will do.

**Comment by TheRealFroggo** [comment]
Textures are working, Just not with Optifine
