### ISSUE TITLE
Doom Mod Server Error

### ISSUE THREAD

**Issue by Strumero** [AzureDoom/AzureDoom-Doom-Mod#3]
[debug.log](https://github.com/AzureDoom/AzureDoom-Doom-Mod/files/4906564/debug.log)
[latest.log](https://github.com/AzureDoom/AzureDoom-Doom-Mod/files/4906565/latest.log)

**Comment by AzureDoom** [comment]
Mod version? MC verison?

**Comment by AzureDoom** [comment]
This issue has been fixed.
