### ISSUE TITLE
BFG damage  problems

### ISSUE THREAD

**Issue by 48004800** [AzureDoom/AzureDoom-Doom-Mod#30]
![2021-02-15_11 53 20](https://user-images.githubusercontent.com/78255094/107903511-6c672f80-6f84-11eb-9e2b-0f5eff297d16.png)
BFG does very little damage to some hostile entities, only 4

![2021-02-15_11 54 26](https://user-images.githubusercontent.com/78255094/107903567-8ef94880-6f84-11eb-9661-32556285d3f3.png)

**Comment by 48004800** [comment]
I've tried many times. It's really a problem with BFG.

**Comment by AzureDoom** [comment]
It's the armor vaule being respected

**Comment by 48004800** [comment]
I've tried higher armor on other entities, but the damage is more than 4

**Comment by 48004800** [comment]
![2021-02-15_11 58 15](https://user-images.githubusercontent.com/78255094/107903803-19da4300-6f85-11eb-9875-6a72e5339f6e.png)
![2021-02-15_11 58 18](https://user-images.githubusercontent.com/78255094/107903806-1b0b7000-6f85-11eb-8c71-1d68baf4f97b.png)

**Comment by 48004800** [comment]
Does this gun have IFF function?
This function doesn't seem perfect

**Comment by 48004800** [comment]
![2021-02-15_12 23 03](https://user-images.githubusercontent.com/78255094/107905053-8f93de00-6f88-11eb-8a2f-963d45ea25a9.png)
It's strange that this gun does a lot of damage to this big guy
Much more damage than husk     Their armor is not much different

**Comment by AzureDoom** [comment]
I do a check for if monster entity so it doesn't hurt passive. 10 to 1 that mob isn't using MonsterEnity.

**Comment by 48004800** [comment]
Wouldn't it be better for you to judge the enemy and ourselves by the attack target of the entity

**Comment by 48004800** [comment]
> I do a check for if monster entity so it doesn't hurt passive. 10 to 1 that mob isn't using MonsterEnity.
I also asked a question
damage to husk and ICON OF SIN
