### ISSUE TITLE
Mod crashes on server side

### ISSUE THREAD

**Issue by ModernGamingWorld** [AzureDoom/AzureDoom-Doom-Mod#32]
[crash-2021-03-03_10.42.58-server.txt](https://github.com/AzureDoom/AzureDoom-Doom-Mod/files/6077848/crash-2021-03-03_10.42.58-server.txt)

**Comment by AzureDoom** [comment]
Can you please paste that to gist or pastebin?

**Comment by ModernGamingWorld** [comment]
https://gist.github.com/ModernGamingWorld/3ca1756f960df3e2be046fa67c9c1cd6

**Comment by AzureDoom** [comment]
Thank you, will be fixed in tonights update with the enchantment fixes
