### ISSUE TITLE
suggestions lower volume for doom

### ISSUE THREAD

**Issue by IchigoGames** [AzureDoom/AzureDoom-Doom-Mod#36]
a few people my self in included have noticed how much louder doom mobs are compared to other mobs you allmost have to turn the slider for hostel mobs down to 0 to get the doom mobs to not be loud its not just the mobs tho the blast and gun shots are also very loud.

**Comment by AzureDoom** [comment]
This is should already be lowered in the newest version, I had normalized all sounds but I will look again here later.

**Comment by IchigoGames** [comment]
oh ok
