### ISSUE TITLE
error

### ISSUE THREAD

**Issue by m4kr1** [AzureDoom/AzureDoom-Doom-Mod#37]
Error loading mods
1 error has occurred during loading
Doom Mod (doomweapon) has failed to load correctly
java.lang.NoClassDefFoundError:
-------------------------------------------------------------------------------------------------------------------------------------------------
That's what it says. I use Tlauncher.
Does the mod not work on cracked minecraft?

**Comment by m4kr1** [comment]
I also installed the newest version of the mod called MCDoom-Mod-1.16.5-3.9.11.jar

**Comment by AzureDoom** [comment]
Guess, what you're my first ban! Buy the game fucking pirate.
