### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Curt69** [AzureDoom/AzureDoom-Doom-Mod#4]
My game crashes when I encounter the Arch-vile.  I was hosting a LAN game and it crashed when the person I was playing with encountered the Arch-vile also. Besides this issue, this is a very good mod, Love it.

**Comment by AzureDoom** [comment]
I need a log as Im fairly certain you are using an old verison where this is already resolved

**Comment by AzureDoom** [comment]
Was I right @Curt69?

**Comment by Curt69** [comment]
Yes, after deleting the version I had and getting the new updated version all problems were fixed.  Sorry for troubling you. I'm new at playing with mod's, and pc gaming in general.  Thanks for the help. I love your mod.
    On Sunday, July 12, 2020, 12:27:31 PM EDT, AzureDoom <notifications@github.com> wrote:  
 
 


Was I right @Curt69?
