### ISSUE TITLE
No Class Definition Error (Java.lang.NoClassDefFoundError)

### ISSUE THREAD

**Issue by Endrez42** [AzureDoom/AzureDoom-Doom-Mod#41]
No idea what seems to be causing this other than it may be caused by Optifine incompatibility, though uninstalling optifine did not resolve the issue.

Hopefully you can figure this out, because the updated Marauder would be perfect for a boss battle with adjusted stats.

[crash-2021-04-03_02.40.07-fml.txt](https://github.com/AzureDoom/AzureDoom-Doom-Mod/files/6252070/crash-2021-04-03_02.40.07-fml.txt)

**Comment by AzureDoom** [comment]
Your Forge is a ton, like A TON outdated.

**Comment by Endrez42** [comment]
Weird. To my knowledge I was using the latest version for 1.16.5.

Thanks for the heads up.

**Comment by AzureDoom** [comment]
No 1.16.5 got a 36.1 release last month and even before that there was 36.0.40ish, your on like 36.0.6

**Comment by Endrez42** [comment]
Hm. I've repeatedly tried to update forge to this version, and am still getting this error. Replaced modpack.jar, replaced the version and such files in Bin and such with the new versions and even got a fresh copy of minecraft.jar.

No idea what step I'm missing in regards to updating forge. 

If you have any idea, help would be appreciated. Perhaps there's a guide out there but I haven't been able to find it for updating forge inside of a modpack.

I will attempt to recreate the modpack with updated forge and see if it persists.

**Comment by Endrez42** [comment]
Nvm. Figured it out. Thanks for the help.
