### ISSUE TITLE
Weapons not consuming their respective ammo items upon reloading when said ammo is on off-hand slot

### ISSUE THREAD

**Issue by Cipher95** [AzureDoom/AzureDoom-Doom-Mod#42]
I came to know this issue when my friends told me about it (We're playing on a modded server with this mod). I went onto a test world and selected a couple of weapons, including the Crucible Sword and one of the Chainsaws (Eternal). I fired each one for a period of time, used the melee weapons in the same regard. Ran three tests: First would be the ammo in inventory - Works as usual. Second is ammo on off-hand slot - It reloads the weapon but does not use up the ammo items. Third I split the ammo, one on off-hand, one in inventory - It prioritizes the ammo in inventory first.

We're using version 3.10.0, Forge version, 1.16.5.
We did have other mods installed, however I tested both with other mods and with just this mod alone, and the issue still persists.

**Comment by AzureDoom** [comment]
How is this just now getting found?? lol will be patched in the next update which is currently going to be a major version jump.
