### ISSUE TITLE
Server Crash from Ticking entity mod.azure.doom.entity.ai.goal.DemonAttackGoal

### ISSUE THREAD

**Issue by IchigoGames** [AzureDoom/AzureDoom-Doom-Mod#43]
Minecraft 1.16.5
Forge 36.1.4
MCDoom-Mod-1.16.5-3.10.0
Crash Report https://pastebin.com/5ZJV60MC

description Player told me he had a mob with over 2k health in his overworld base this player lives near a biome that was turned from overwortd to nether so it could be that this mob was never meant to be in overworld but as soon as he attempted to attack it server Crashed

**Comment by IchigoGames** [comment]
if you need anymore info let me know.

**Comment by AzureDoom** [comment]
`com.performant.coremod.entity.ai.CustomGoalSelector` this is a performant issue as they modifying a base Minecraft. I can't fix this, it will need fixed on their side.

**Comment by IchigoGames** [comment]
oh ok

**Comment by AzureDoom** [comment]
I can add a few null checks though in the next update.
