### ISSUE TITLE
Compatibility with Numina (Modular Powersuits Core/Dependency) 

### ISSUE THREAD

**Issue by Throne-Actual** [AzureDoom/AzureDoom-Doom-Mod#44]
I noticed the Doom suits wouldn't render correctly - after removing chunks of mods at a time I deduced it was Numina (Numina-1.16.4-2.0.6) for the Modular Powersuits Mod. Not sure if this would be a difficult fix/or if you'd have any intention of fixing for compatibility issues but it'd be cool/appreciated.

-Thanks for all of your work so far

**Comment by AzureDoom** [comment]
You will need to make an issue with them, since they are modifying things https://github.com/MachineMuse/Numina/issues
