### ISSUE TITLE
Warped Forest overrun

### ISSUE THREAD

**Issue by TheSpamMiner** [AzureDoom/AzureDoom-Doom-Mod#45]
The Warped Forest is impossible to use as an Enderman hunting area because of all the Doom mobs spawning there. No Endermen even spawn anymore. Since I have Biomes O Plenty, there's more nether biomes than I can list off to fill a whitelist. That's a problem because #nether has higher priority than !minecraft:warped_forest. 

Can you make it so I can pick a single biome to subtract from the whole #nether tag without filling a whitelist with everything except it?

**Comment by AzureDoom** [comment]
I can not
