### ISSUE TITLE
Heavy Cannon I-Frames and Quiet Gun Sounds

### ISSUE THREAD

**Issue by CFlatFlat** [AzureDoom/AzureDoom-Doom-Mod#47]
1. The heavy cannon respects i-frames unlike the other automatic weapon, making it relatively weak and it causes you to waste a lot of bullets.

2. The guns sounds are rather quiet. I saw that a closed issue mentioned them being too loud before, though. Perhaps they could have their own volume slider so users could tweak it as they saw fit.

**Comment by AzureDoom** [comment]
1. Normal.
2. No I put them under vanilla sliders and will not add my own.
