### ISSUE TITLE
Armor textures are broken.

### ISSUE THREAD

**Issue by GamerRaven81** [AzureDoom/AzureDoom-Doom-Mod#48]
Seems to be affecting all armors.
Classic Doom Armor
![2021-06-02_07 31 41](https://user-images.githubusercontent.com/77138299/120473203-c560a500-c374-11eb-9237-f414c1bdaa2f.png)

**Comment by AzureDoom** [comment]
Version? Log? Peovide details

**Comment by GamerRaven81** [comment]
MCDoom-Mod-1.16.5-3.10.0.jar 

Log of what? It's not a crash issue. It's a texture issue. Which I provided an image of.

**Comment by AzureDoom** [comment]
No log no help

**Comment by AzureDoom** [comment]
![2021-06-02_18 05 22](https://user-images.githubusercontent.com/7415711/120558232-2b791680-c3cd-11eb-995e-dbe5c3fa440a.png)
shit works just fine btw.
