### ISSUE TITLE
MCDoom-Fabric-1.16.5-4.0.0-beta2 Spawning Issue , Ai Issue

### ISSUE THREAD

**Issue by Demiosis** [AzureDoom/AzureDoom-Doom-Mod#52]
-Config list currently missing a big number of monsters that cannot be controlled.
-Summoner and Gore nest do not follow the config list and will spawn disabled mobs.
-Lost souls , Cacodemons and pain elemental simply do not spawn at all.
-Revenant and Revenant 2016 Still kill each others and anyone upon spawning.

**Comment by AzureDoom** [comment]
- variants system is being used
- intended
- yes they do just rarely.
- already fixed, update to latest beta.
