### ISSUE TITLE
-

### ISSUE THREAD

**Issue by red2blue** [AzureDoom/AzureDoom-Doom-Mod#57]
-

**Comment by AzureDoom** [comment]
This is a 1.17 achievement bug

**Comment by red2blue** [comment]
Don't think it's a bug of minecraft if it only happens on your mod and I have 150+ mods installed.

**Comment by AzureDoom** [comment]
It's due to a change in achievements. I just don't care to fix right now.

**Comment by red2blue** [comment]
I see thank you

**Comment by AzureDoom** [comment]
This was fixed in latest version
