### ISSUE TITLE
[suggestion] NetherEX compatability

### ISSUE THREAD

**Issue by MasterSloth1** [AzureDoom/AzureDoom-Doom-Mod#6]
as the title says, I assume your making the mobs spawn in a specific biome instead of a specific dimension when nether ex is installed it adds tons of new biomes to the nether preventing your mobs from spawning, they do spawn but only in the nether biome and not nether ex biomes :/

**Comment by MasterSloth1** [comment]
ah i forgot this is for the 1.15.2 version

**Comment by AzureDoom** [comment]
Should be easy to do. Will do it here after the Fabric port.

**Comment by MasterSloth1** [comment]
nice thank you for the quick patch, i can confirm it is working as of version AzureDooms-Doom-Mod-1.15.2-2.4.1.jar
