### ISSUE TITLE
[Bug] Crash upon killing zombieman (Fabric 1.17.1, 4.0.6)

### ISSUE THREAD

**Issue by madimura20** [AzureDoom/AzureDoom-Doom-Mod#61]
I'm not sure if it's due to a mod conflict with Physics Mod or using Sodium renderer, but for some reason the game freezes and crashes when I kill a Zombieman or Chaingunner. I've tested to see if this affects any of the other mobs, but the crash only happens with zombieman, chaingunner, and the other mobs that are similar to those two. When I got to testing the Chaingunner, I got the same crash as with the Zombieman.

Let me know if there's any more info or tests needed

Crash log:

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 8/28/21, 1:49 AM
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: Index 1200 out of bounds for length 1200
	at Not Enough Crashes deobfuscated stack trace.(1.17+build.10)
	at net.minecraft.client.render.WorldRenderer.renderFast(WorldRenderer:7247)
	at net.minecraft.client.render.WorldRenderer.handler$zcf000$renderLayer(WorldRenderer:6991)
	at net.minecraft.client.render.WorldRenderer.renderLayer(WorldRenderer:4833)
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1166)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:1026)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:810)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1112)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:728)
	at net.minecraft.client.main.Main.main(Main:217)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_761.renderFast(class_761.java:7247)
	at net.minecraft.class_761.handler$zcf000$renderLayer(class_761.java:6991)
	at net.minecraft.class_761.method_3251(class_761.java:4833)
	at net.minecraft.class_761.method_22710(class_761.java:1166)
	at net.minecraft.class_757.method_3188(class_757.java:1026)

-- Patchouli Book Info --
Details:
	Patchouli open book context: n/a
Stacktrace:
	at net.minecraft.class_128.handler$bne000$fillPatchouliContext(class_128.java:1521)
	at net.minecraft.class_128.<init>(class_128.java:37)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Affected level --
Details:
	All players: 1 total; [class_746['Mademoiselle_GDP'/460, l='ClientLevel', x=-1331.40, y=62.50, z=109.04]]
	Chunk stats: 1024, 432
	Level dimension: minecraft:overworld
	Level spawn location: World: (-224,69,112), Section: (at 0,5,0 in -14,4,7; chunk contains blocks -224,-64,112 to -209,319,127), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 813427 game time, 19403 day time
	Server brand: fabric
	Server type: Integrated singleplayer server

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, atbyw_mi/mod_interaction_resources, jolicraft-e1620.zip, visualoverhaul/fancyfurnace, visualoverhaul/coloredwaterbucket, charmonium/journeyman, betterbeds/fancybeds

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2766488904 bytes (2638 MiB) / 5301600256 bytes (5056 MiB) up to 12884901888 bytes (12288 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 1.99
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1050
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1c8d
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7111
	Graphics card #1 name: Intel(R) UHD Graphics 620
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x5917
	Graphics card #1 versionInfo: DriverVersion=26.20.100.6913
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 22599.89
	Virtual memory used (MB): 16923.42
	Swap memory total (MB): 6400.00
	Swap memory used (MB): 50.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		additionaladditions: Additional Additions 2.1.1
		additionalbars: Additional Bars 2.1.1
		adorn: Adorn 2.1.3+1.17.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.3.11
		animal_feeding_trough: Animal Feeding Trough 1.0.2
		architectury: Architectury 2.4.26
		artifality: Artifality 0.3.3
		atbyw: All The Blocks You Want (ATBYW) 1.5.2
		bclib: BCLib 0.3.1
		beebuddy: Bee Buddies 1.1.3+1.17.1
		bendy-lib: Bendy api 2.0.2
		better_wandering_trader: Better Wandering Trader 1.7.0
		betterbeds: Better Beds 1.2.0
		betterend: Better End 0.11.0-pre
		betterf3: BetterF3 1.1.5
		bettermineshafts: YUNG's Better Mineshafts 1.17-1.0.1
		betternether: Better Nether 5.1.3
		betterstrongholds: YUNG's Better Strongholds 1.17-1.1.1
		betterthirdperson: Better Third Person 1.5.0
		blockus: Blockus 2.2.8+1.17.1
		blue_endless_jankson: jankson 1.2.1
		cardinal-components-base: Cardinal Components API (base) 3.0.0
		cardinal-components-entity: Cardinal Components API (entities) 3.0.0
		cavebiomes: Cave Biomes 0.6.3
		charm: Charm 3.3.0
		charmonium: Charmonium 3.3.0
		chipped: Chipped 1.1.1
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v5 5.0.38
		cmdkeybind: Command Macros 1.5.2-1.17
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		croptopia: Croptopia 1.6.1
		ctm: ConnectedTexturesMod for Fabric 0.5.1+1.17
		culinaire: Culinaire 2.1.1
		dawn: Dawn API 2.0.6
		decorative: Decorative 4.1.1
		doom: Doom Fabric 4.0.6
		dungeons_arise: When Dungeons Arise 2.1.47-fabric
		dynamicfps: Dynamic FPS 2.0.5
		earthtojavamobs: Earth2Java 1.7.2+1.17
		elementalcreepers: Elemental Creepers: Refabricated 1.4.0
		emotecraft: Emotecraft 2.0.9
		extrarecords-core: Extrarecords Core 2.0.1
		extrarecords-fnf: Extrarecords FNF 1.0
		extrasounds: Extra Sounds 1.4.1
		extrasponges: ExtraSponges 1.1.0
		fab: Foodables 1.0.8
		fabric: Fabric API 0.39.2+1.17
		fabric-api-base: Fabric API Base 0.3.0+8d89ed5432
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+2f75c6ce18
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.0+b06cb95b18
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.0+211ddf9518
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.2+62e33f4118
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57718
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b446318
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-language-kotlin: Fabric Language Kotlin 1.6.4+kotlin.1.5.30
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446318
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+2e8bd82f18
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612118
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96918
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446318
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.1+b06cb95b18
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446313
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa18
		fabric-rendering-v1: Fabric Rendering (v1) 1.8.0+b06cb95b18
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+155f865c18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.1+b06cb95b18
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.1.2+96bf6a7e18
		fabricloader: Fabric Loader 0.11.6
		fallflyinglib: FallFlyingLib 3.0.0-beta.2
		fallingtree: FallingTree 2.13.0
		ferritecore: FerriteCore 3.0.3
		fiber: fiber 0.23.0-2
		firstperson: FirstpersonModel 2.0.2
		forgottenrecipes: Forgotten Recipes 1.0.2
		geckolib3: Geckolib 3.0.13
		gobber2: Gobber2 2.4.40
		human_reborn: Human Reborn 1.0.1
		hwg: Happiness is a Warm Gun 1.0.13
		hydrogen: Hydrogen 0.3
		illuminations: Illuminations 1.6.4
		indium: Indium 1.0.0+mc1.17.1
		inmis: Inmis 2.3.1-1.17
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		kirin: Kirin UI 1.9.1
		kyrptconfig: Kytpt Config 1.1.10-1.17
		lakeside: Lakeside 1.1.0+1.17
		lambdynlights: LambDynamicLights 2.0.2+1.17
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.1.3+1.17.1
		libninepatch: LibNinePatch 1.1.0
		lithium: Lithium 0.7.4
		magick: Magick: Potions and Pearls 1.0.5
		magna: Magna 1.5.5-1.17-pre4
		mavm: More Axolotl Variants Mod 1.0.3a
		maybe-data: Maybe data 1.0.1-1.17
		mdg: mdg 1.0.0
		megane: megane 5.2.1
		megane-base: megane-base 5.2.1
		megane-fabric-transfer: megane-fabric-transfer 5.2.1+1.1.0-3fe74aa118
		megane-runtime: megane-runtime 5.2.1
		megane-vanilla: megane-vanilla 5.2.1+1.17.1
		midnightlib: MidnightLib 0.2.3
		minecraft: Minecraft 1.17.1
		modmenu: Mod Menu 2.0.6
		mojangster: Mojangster 1.17-1.3.0
		more_gems: More Gems 1.2.33
		moreboots: More Boots 1.0.0
		morevillagers-fabric: MoreVillagersFabric 2.0.4-SNAPSHOT
		mostructures: Mo' Structures 1.2.1-1.17
		nbtcrafting: NBT Crafting 2.0.20+mc1.17.1
		notenoughanimations: NotEnoughAnimations 1.3.0
		notenoughcrashes: Not Enough Crashes 3.4.4+1.17
		omega-config: OmegaConfig 1.0.8
		onsoulfire: On Soul Fire 1.17-2
		openloader: OpenLoader 2.0.1
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.30
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.2
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.2
		oxidizelib: OxidizeLib 1.1.0
		patchouli: Patchouli 1.17-54-FABRIC
		paxi: Paxi 1.17-1.2
		periodic: Periodic 0.4.0
		pettable: Pettable 1.2.0
		physicsmod: Physics Mod 2.5.6
		player_transport_ducts: Player Transport Ducts 1.0.2
		playerabilitylib: Pal 1.3.0-nightly.1.17-rc1
		prefab: Prefab 2.1.2
		presencefootsteps: Presence Footsteps r32-1.17-rc1
		promenade: Promenade 2.1.2
		prone: prone 0.1.4
		pugh_lib: Pugh Lib ${version}
		pugh_tools: Pugh Tools ${version}
		repurposed_structures: Repurposed Structures 2.3.2+1.17.1
		riverredux: River Redux 0.2.0
		roughlyenoughitems: Roughly Enough Items 6.0.275-alpha
		satin: Satin 1.6.4
		sentimentality3: Sentimentality 3 1.3.2
		simplyimprovedterrain: Simply Improved Terrain 0.4.0.3-Fabric-1.17
		skylorlib: SkyLib 1.0.3
		sodium: Sodium 0.3.0+build.5
		spruceui: SpruceUI 3.2.0+1.17
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		stoneholm: Stoneholm 1.3
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 2.0.0
		terraform-config-api-v1: Terraform Config API (v1) 2.0.0
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 2.0.0
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.4
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 2.0.0
		terraform-tree-api-v1: Terraform Tree API (v1) 2.0.0
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		the_bumblezone: The Bumblezone - Fabric 3.0.9+1.17.1
		things: Things 0.2.5
		transliterationlib: TRansliterationLib 1.1.0
		traverse: Traverse 4.0.0-beta.2
		trinkets: Trinkets 3.0.2
		vanilla-hammers: Vanilla Hammers 3.1.2-1.17
		vanillaexcavators: Vanilla Excavators 1.1.0
		vanillaplusbiomes: Vanilla Plus Biomes 0.3.2
		villagernames: Villager Names 2.0.0
		villagersleashed: Villagers Leashed! 1.0
		visualoverhaul: VisualOverhaul 3.3.0
		wands: Building Wands 2.1.4
		wildfire_gender: Wildfire's Female Gender Mod 2.6.1
		winged: Winged Mod 1.17-3.0.0-beta.2
		woods_and_mires: Woods and Mires 1.1.0+1.17
		wthit: wthit 3.8.1
		xaerominimap: Xaero's Minimap 21.16.0
		xaeroworldmap: Xaero's World Map 1.16.0
		yungsapi: YUNG's API 1.17-Fabric-16
	Launched Version: fabric-loader-0.11.6-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1050/PCIe/SSE2 GL version 3.2.0 NVIDIA 471.11, NVIDIA Corporation
	Window size: 3840x2160
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, Fabric Mods, atbyw_mi/mod_interaction_resources (incompatible), file/jolicraft-e1620.zip, visualoverhaul/fancyfurnace, visualoverhaul/coloredwaterbucket, charmonium/journeyman, betterbeds/fancybeds
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
	Player Count: 1 / 8; [class_3222['Mademoiselle_GDP'/460, l='ServerLevel[New World, once again]', x=-1331.40, y=62.50, z=109.04]]
	Data Packs: vanilla, atbyw_mi/mod_interaction_resources (incompatible), Fabric Mods, file/biomecavesv1-2.zip, file/Repurposed_Structures-Charm-v2.zip
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Fabric Loader (fabricloader)

**Comment by AzureDoom** [comment]
Physics mod issue
