### ISSUE TITLE
[1.17.1] NBTCrafting / REI

### ISSUE THREAD

**Issue by red2blue** [AzureDoom/AzureDoom-Doom-Mod#63]
MC 1.17.1 
Latest MCDOOM

I wish you didnt disable comments on the closed issue.

So does MCdoom use NBTCrafting or does it not? 

Because when I remove Mcdoom REI starts magically working again. I do believe this has to do with your mod.

**Comment by AzureDoom** [comment]
It's used for the patchouli book.
No I'm not removing it.
No I don't care about rei not working, take it up with nbt crafting as I'm on latest of it. End of story

**Comment by red2blue** [comment]
Wow youre a piece of shit lmfao. Sorry I'm trying to fix my modpack with 10k downloads. your mod is buggy as fuck anyways, bye bye mcdoom.

**Comment by AzureDoom** [comment]
K
