### ISSUE TITLE
error while trying too load into my server world

### ISSUE THREAD

**Issue by LoudManGames** [AzureDoom/AzureDoom-Doom-Mod#64]
[crash-2021-09-04_15.28.05-client.txt](https://github.com/AzureDoom/AzureDoom-Doom-Mod/files/7110399/crash-2021-09-04_15.28.05-client.txt)

playing with the aqm2 modpack and was told too send the issue this way for help.

**Comment by AzureDoom** [comment]
I see nothing in the log to say it's this mod causing the crash, please state what you were doing when it crashed.

**Comment by LoudManGames** [comment]
just trying too load a new world and the modpack owner told me too bring it this way. sry if theres a mixup.

**Comment by AzureDoom** [comment]
Yeah, it's not this mod (you are behind an update anyways) I just tested in a built jar and was able to join a new world just fine. Tell the pack dev to update.
