### ISSUE TITLE
Doom Items Mod (doomweapon) encountered an error during the load_registries event phase

### ISSUE THREAD

**Issue by thorgod949** [AzureDoom/AzureDoom-Doom-Mod#7]
[crash-2020-09-06_03.31.50-server.txt](https://github.com/AzureDoom/AzureDoom-Doom-Mod/files/5179041/crash-2020-09-06_03.31.50-server.txt)
[latest.log](https://github.com/AzureDoom/AzureDoom-Doom-Mod/files/5179043/latest.log)
Just Error V
https://pastebin.pl/view/6538e8aa

Minecraft 1.15.2
Crashes on startup

**Comment by AzureDoom** [comment]
Fixed in 2.5.4

**Comment by thorgod949** [comment]
Thanks man
