### ISSUE TITLE
Incompatability with Extened Nether

### ISSUE THREAD

**Issue by thorgod949** [AzureDoom/AzureDoom-Doom-Mod#8]
Full error log - https://paste.ee/p/nCKIQ
just Error - https://paste.ee/p/r1mp2

Talked to the auther of Extened Nether (I think) and "the mod tried to add compatibility to extended nether" There may be a fix on his end but thought I would report it here as well.

**Comment by AzureDoom** [comment]
Nah the fix will just need done on my end. This will be fixed with the next update, which will be out sometime tomorrow as I'm currently in the middle of a combat update for the mobs.
